language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=16 # 16 minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-27
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 180
  - adb devices
  - adb shell input keyevent 82 &

script:
  - chmod +x ./gradlew
  - ./gradlew test
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)



